export type Design = {
  slug: string
  title: string
  src: string
  alt: string
}

export const designs: Design[] = [
  { slug: 'siam-garden-toile-calming-blue', title: 'Siam Garden Toile on Calming Blue', src: 'https://img.spoonflower.com/c/19552492/p/f/m/vC2DIi1eATHRnb90yLV1QKnsS-qezG6F8bgP46pp0UTNZKHuMjoD/Siam_Garden_Toile_on_Calming_Blue.jpg', alt: 'Siam Garden Toile on Calming Blue' },
  { slug: 'jungle-monkeys-multi-soft-pink', title: 'Jungle Monkeys Forest Toile - Multi on Soft Pink Ground', src: 'https://img.spoonflower.com/c/19832572/p/f/m/G8WRFTdEIZlbMaOuixWidUYSbGHRUDrUNbCnpYxA3pjdQlMAhaYs/Jungle_Monkeys_Forest_Toile_-_Multi_on_soft_Pink_ground.jpg', alt: 'Jungle Monkeys Forest Toile Multi on Soft Pink Ground' },
  { slug: 'frangipani-tropical-damask-soft-peach-cream', title: 'Frangipani Tropical Damask Soft Peach & Cream', src: 'https://img.spoonflower.com/c/19223719/p/f/m/1tvxXwt0QJd2q6wBEdm7sWK_lMpqwDERuwCNqpX8ar2w-3VTPDL3/Frangipani_Tropical_Damask_Soft_Peach_%26_Cream.jpg', alt: 'Frangipani Tropical Damask Soft Peach and Cream' },
  { slug: 'siam-garden-toile-lime-and-cream', title: 'Siam Garden Toile - Lime and Cream', src: 'https://img.spoonflower.com/c/19552876/p/f/m/F7Mt1cNjTYFdwdz2y98qdY7s0hjcdlnTBlKu4ExicwY5KJ6_kNcy/Siam_Garden_Toile_-_Lime_and_Cream.jpg', alt: 'Siam Garden Toile Lime and Cream' },
  { slug: 'lotus-nouveau-cream-on-peach', title: 'Lotus Nouveau - Cream on Peach Ground', src: 'https://img.spoonflower.com/c/20808693/p/f/m/r6ixHgImFVnxBtxCNQlyZAnKw26u5ilr87wY4-wVjLE9M4WmUOgB/Lotus_Nouveau_-_cream_on_peach_ground.jpg', alt: 'Lotus Nouveau Cream on Peach Ground' },
  { slug: 'lotus-nouveau-cream-on-azure', title: 'Lotus Nouveau - Cream on Azure Ground', src: 'https://img.spoonflower.com/c/20808692/p/f/m/IK8tFXFpU1TAfxDyFeg_Jw81p7rVIKXo6qlbyjDk1FWMoJKqEW4x/Lotus_Nouveau_-_cream_on_azure_ground.jpg', alt: 'Lotus Nouveau Cream on Azure Ground' },
  { slug: 'lotus-nouveau-peach-on-cream', title: 'Lotus Nouveau - Peach on Cream Ground', src: 'https://img.spoonflower.com/c/20808691/p/f/m/DHqgG8P49ChHqUmapAV3xm2FEGy-NEzCXNXX7GsuXNS5P45c_Jlg/Lotus_Nouveau_-_peach_on_cream_ground.jpg', alt: 'Lotus Nouveau Peach on Cream Ground' },
  { slug: 'lotus-nouveau-azure-on-cream', title: 'Lotus Nouveau - Azure on Cream Ground', src: 'https://img.spoonflower.com/c/20808389/p/f/m/WXGr29nt--hN01aWJ7tYqCo04AEGaHuaNxzWa0incLK8EszTerAn/Lotus_Nouveau_-_azure_on_cream_ground.jpg', alt: 'Lotus Nouveau Azure on Cream Ground' },
  { slug: 'islands-of-andaman-soft-blue-khaki', title: 'Islands of Andaman Coastal Toile - Soft Blue & Khaki', src: 'https://img.spoonflower.com/c/19872947/p/f/m/OdjoNVGQaVQTqvH4-eIBbosmUbMiBPU2JJ0_TO862j-4gyCOpXIV/Islands_of_Andaman_Coastal_Toile_-_Soft_Blue_%26_Khaki.jpg', alt: 'Islands of Andaman Coastal Toile Soft Blue and Khaki' },
  { slug: 'islands-of-andaman-soft-pink-khaki', title: 'Islands of Andaman Coastal Toile - Soft Pink & Khaki', src: 'https://img.spoonflower.com/c/19872714/p/f/m/apxY6MSbCFNgARyslvIwUgyi4RPdg8ZdEbg8pphs-1y7r0-9fHzm/Islands_of_Andaman_Coastal_Toile_-_Soft_Pink_%26_Khaki.jpg', alt: 'Islands of Andaman Coastal Toile Soft Pink and Khaki' },
  { slug: 'herbaceous-floral-berries-leaves-multi', title: 'Herbaceous Floral Berries & Leaves Cottagecore Botanical - Multi', src: 'https://img.spoonflower.com/c/19530576/p/f/m/EyMI3EMutaF7phv7yrFyT9m9SpI24bRDiTgb2ql9b32RmZNRK43I/Herbaceous_Floral_Berries_%26_Leaves_Cottagecore_Botanical_Pattern_-_Multi.jpg', alt: 'Herbaceous Floral Berries and Leaves Cottagecore Botanical Multi' },
  { slug: 'jungle-monkeys-lime-soft-pink', title: 'Jungle Monkeys Forest Toile - Lime on Soft Pink Ground', src: 'https://img.spoonflower.com/c/19832557/p/f/m/LSYTVrJBARDYk7vXO2NSW9Vf1HaqbGKB6xcpM5eVRVIytfNMyU_d/Jungle_Monkeys_Forest_Toile_-_Lime_on_soft_Pink_ground.jpg', alt: 'Jungle Monkeys Forest Toile Lime on Soft Pink Ground' },
  { slug: 'jungle-monkeys-soft-pink', title: 'Jungle Monkeys Forest Toile - Soft Pink', src: 'https://img.spoonflower.com/c/19825246/p/f/m/1dwU9yt0xTlnr-TzKZkcrnWRK-nOVOJAQtSGftH4wz-MBTWKxRSf/Jungle_Monkeys_Forest_Toile_-_Soft_Pink.jpg', alt: 'Jungle Monkeys Forest Toile Soft Pink' },
  { slug: 'jungle-monkeys-soft-blue', title: 'Jungle Monkeys Forest Toile - Soft Blue', src: 'https://img.spoonflower.com/c/19825192/p/f/m/b8MIzNLTZtpXTmq43xFQmUUEtMrvsc0korv7Wy3AODNii0JZ-ph9/Jungle_Monkeys_Forest_Toile_-_Soft_Blue.jpg', alt: 'Jungle Monkeys Forest Toile Soft Blue' },
  { slug: 'jungle-monkeys-multi', title: 'Jungle Monkeys Forest Toile - Multi', src: 'https://img.spoonflower.com/c/19818536/p/f/m/ZDbh7QSt5tmkM27r3W-ja2g-shGnpUoGJ0gOVo4lReY_ssHsFhnP/Jungle_Monkeys_Forest_Toile_-_Multi.jpg', alt: 'Jungle Monkeys Forest Toile Multi' },
  { slug: 'handdrawn-scallop-waves-cream-on-khaki', title: 'Handdrawn Scallop Waves - Cream on Khaki Ground', src: 'https://img.spoonflower.com/c/19653676/p/f/m/Wkf7d1bNC4rtPdoO88yS8xjv6pBlImdw1SkHyflJWgG_KDFrbKoQ/Handdrawn_Scallop_Waves_-_Cream_on_Khaki_ground.jpg', alt: 'Handdrawn Scallop Waves Cream on Khaki Ground' },
  { slug: 'handdrawn-scallop-waves-soft-blue-on-brown', title: 'Handdrawn Scallop Waves - Soft Blue on Brown Ground', src: 'https://img.spoonflower.com/c/19653671/p/f/m/KegmgquZ9QtCLQXBqHECVv4IfqFCqH6pyp2OMaKGffM9dnVuxqsw/Handdrawn_Scallop_Waves_-_Soft_Blue_on_Brown_ground.jpg', alt: 'Handdrawn Scallop Waves Soft Blue on Brown Ground' },
  { slug: 'scallop-waves-calming-blue', title: 'Scallop Waves on Calming Blue', src: 'https://img.spoonflower.com/c/19653656/p/f/m/Yn6LxW-V_JlgrYoN2AbejN-2qDAbc_lDVZ0jRU1QzgMp1_zUgIzx/Scallop_Waves_on_Calming_Blue.jpg', alt: 'Scallop Waves on Calming Blue' },
  { slug: 'handdrawn-scallop-waves-khaki-on-pink', title: 'Handdrawn Scallop Waves - Khaki on Pink Ground', src: 'https://img.spoonflower.com/c/19653600/p/f/m/u-dPY7GeLSEUbzre5UOhlbYBdi2rQyfAtWeeyWGCwhbdCOfctqAv/Handdrawn_Scallop_Waves_-_Khaki_on_Pink_ground.jpg', alt: 'Handdrawn Scallop Waves Khaki on Pink Ground' },
  { slug: 'pomelo-grove-chintz-lime-brown-cream-khaki', title: 'Pomelo Grove Chintz - Lime Brown and Cream on Khaki Ground', src: 'https://img.spoonflower.com/c/19647719/p/f/m/GMOZnJoRrVdeHX6XBXtNggHb4zullnJDxR0TTzcwO2BhyhjfxKoh/Pomelo_Grove_Chintz_-_Lime_Brown_and_Cream_on_Khaki_ground.jpg', alt: 'Pomelo Grove Chintz Lime Brown and Cream on Khaki Ground' },
  { slug: 'frangipani-tropical-damask-cream-lime-brown', title: 'Frangipani Tropical Damask - Cream and Lime on Brown Ground', src: 'https://img.spoonflower.com/c/19647505/p/f/m/kN7XUeto7tGYhgwa2hfaGWUvROLXWzEI_wZTq80o1dBeSoHxubia/Frangipani_Tropical_Damask_-_Cream_and_Lime_on_Brown_ground.jpg', alt: 'Frangipani Tropical Damask Cream and Lime on Brown Ground' },
  { slug: 'frangipani-tropical-damask-cream-blue-khaki', title: 'Frangipani Tropical Damask - Cream and Light Blue on Khaki Ground', src: 'https://img.spoonflower.com/c/19647073/p/f/m/Kgs8AYVTHnJy7hb5d8Gn-zH76sjgNJrKZkl3SGXuriq71qtBotff/Frangipani_Tropical_Damask_-_Cream_and_Light_Blue_on_Khaki_ground.jpg', alt: 'Frangipani Tropical Damask Cream and Light Blue on Khaki Ground' },
  { slug: 'lotus-flow-cream-brown-on-pink', title: 'Lotus Flow - Cream and Brown on Pink Ground', src: 'https://img.spoonflower.com/c/19642223/p/f/m/55APIDpK7Dk_IubYkpZ4s-oAJ6lbjwyGq8FZGENU26-XhYlNXFea/Lotus_Flow_-_Cream_and_Brown_on_Pink_ground.jpg', alt: 'Lotus Flow Cream and Brown on Pink Ground' },
  { slug: 'lotus-flow-pink-brown-on-light-blue', title: 'Lotus Flow - Pink and Brown on Light Blue Ground', src: 'https://img.spoonflower.com/c/19642191/p/f/m/EvvKtsSLCHrJ7J3kXmtH5uDqOpin9fuwQNnNsPOaV4ahwv9CP_Jq/Lotus_Flow_-_Pink_and_Brown_on_Light_Blue_ground.jpg', alt: 'Lotus Flow Pink and Brown on Light Blue Ground' },
  { slug: 'lotus-flow-pink-lime-on-brown', title: 'Lotus Flow - Pink and Lime on Brown Ground', src: 'https://img.spoonflower.com/c/19642088/p/f/m/yMTdK8lI3Z0eLEyYl4Ludo52gxO04r1aPNHOh8GmO696HvZuelu2/Lotus_Flow_-_Pink_and_Lime_on_Brown_ground.jpg', alt: 'Lotus Flow Pink and Lime on Brown Ground' },
  { slug: 'lotus-flow-khaki-cream-on-light-blue', title: 'Lotus Flow - Khaki and Cream on Light Blue Ground', src: 'https://img.spoonflower.com/c/19642056/p/f/m/U8tgdhGybvTBaY9RGG-6w2cC9K2qxh0lexZmomE4s1zF2eq_DQVX/Lotus_Flow_-_Khaki_and_Cream_on_Light_Blue_ground.jpg', alt: 'Lotus Flow Khaki and Cream on Light Blue Ground' },
  { slug: 'frangipani-tropical-damask-calming-blue', title: 'Frangipani Tropical Damask on Calming Blue', src: 'https://img.spoonflower.com/c/19284693/p/f/m/X50ngY0z07c8wxit72Ao69pY_5K-EMfUuLDr5EJzTnQ23P3LXNaU/Frangipani_Tropical_Damask_on_Calming_Blue.jpg', alt: 'Frangipani Tropical Damask on Calming Blue' },
  { slug: 'siam-garden-toile-light-peach', title: 'Siam Garden Toile - Light Peach', src: 'https://img.spoonflower.com/c/19552865/p/f/m/QUFCdzEwXepCv7FLOCFkoUdqiyZJbzdpHbdlb8GsKCquSRBywQ3z/Siam_Garden_Toile_-_Light_Peach.jpg', alt: 'Siam Garden Toile Light Peach' },
  { slug: 'siam-garden-toile-khaki-and-cream', title: 'Siam Garden Toile - Khaki and Cream', src: 'https://img.spoonflower.com/c/19552882/p/f/m/vC2DIi1eATHRnbN1yLV1QKnsS-qezG6F8bgP46pp0UTNZKHuMh8z/Siam_Garden_Toile_-_Khaki_and_Cream.jpg', alt: 'Siam Garden Toile Khaki and Cream' },
  { slug: 'pomelo-grove-chintz-lime-khaki-blue-cream', title: 'Pomelo Grove Chintz - Lime Khaki and Soft Blue on Cream Ground', src: 'https://img.spoonflower.com/c/19588831/p/f/m/G6DB70RSbGzg5U8RgqtzmoA0pEazzUR1c71GyEwhGvHKZieYP_T3/Pomelo_Grove_Chintz_-_Lime_Khaki_and_Soft_Blue_on_Cream_ground.jpg', alt: 'Pomelo Grove Chintz Lime Khaki and Soft Blue on Cream Ground' },
]
