export type Design = {
  slug: string
  title: string
  src: string
  alt: string
}

export const designs: Design[] = [
  { slug: 'soft-prairie-garden-warm-natural-beige', title: 'Soft Prairie Garden Warm Natural Beige', src: 'https://img.spoonflower.com/c/21315760/p/f/m/Y62oy2kbODuHWc6H6tU0x51f-6_va0iNsvay21zhPE4DeHgWSu14/(m)_Soft_Prairie_Garden_Warm_Natural_Beige.jpg', alt: 'Soft Prairie Garden Warm Natural Beige' },
  { slug: 'retro-ditsy-prairie-florals-denim-blue-yellow', title: 'Retro Ditsy Prairie Florals in Muted Denim Blue and Soft Yellow', src: 'https://img.spoonflower.com/c/21375280/p/f/m/ELi9vTI-vwwT7wtLWqOA2LxnYYiWVhrcLPlLLhW0lj_NGQbqYL3a/(s)_Retro_Ditsy_Prairie_Florals_in_Muted_Denim_Blue_and_Soft_Yellow.jpg', alt: 'Retro Ditsy Prairie Florals in Muted Denim Blue and Soft Yellow' },
  { slug: 'country-retro-gingham-cornflower', title: 'Country Retro Gingham Cornflower Muted Blue and Cream', src: 'https://img.spoonflower.com/c/21400079/p/f/m/e7Dn8xhgfBXCm5crn6XJWrNWh5bUwJx6kpdFb9n3H7A3uVkp9yG8/Country_Retro_Gingham_Cornflower_Muted_Blue_and_Cream.jpg', alt: 'Country Retro Gingham Cornflower Muted Blue and Cream' },
  { slug: 'queen-annes-lace-natural-beige', title: "Queen Anne's Lace Ditsy Floral in Natural Beige", src: "https://img.spoonflower.com/c/21460752/p/f/m/k49ugada_i4wk6afI9MSJuNvHUZOWU-YzoaUvqZtWahBVeeZM6Hv/Queen_Anne's_Lace_Ditsy_Floral_in_Natural_Beige.jpg", alt: "Queen Anne's Lace Ditsy Floral in Natural Beige" },
  { slug: 'queen-annes-lace-yellow-mustard', title: "Queen Anne's Lace Ditsy Floral in Warm Yellow and Mustard", src: "https://img.spoonflower.com/c/21460721/p/f/m/k2I5NrGpHfjJ15Qv4QuXcarFL2UeNOKGjhkpHFL-Gh7QvuugoibN/Queen_Anne's_Lace_Ditsy_Floral_in_Warm_Yellow_and_Mustard.jpg", alt: "Queen Anne's Lace Ditsy Floral in Warm Yellow and Mustard" },
  { slug: 'queen-annes-lace-yellow-white', title: "Queen Anne's Lace Ditsy Floral in Warm Yellow and White", src: "https://img.spoonflower.com/c/21460719/p/f/m/5tOp5Fx0I157it8qlnTZCVvRVbkrBtQtLDDYYBirikY5RxyK57c4/Queen_Anne's_Lace_Ditsy_Floral_in_Warm_Yellow_and_White.jpg", alt: "Queen Anne's Lace Ditsy Floral in Warm Yellow and White" },
  { slug: 'queen-annes-lace-blue-cream', title: "Queen Anne's Lace Ditsy Floral in Muted Blue and Cream", src: "https://img.spoonflower.com/c/21460718/p/f/m/7Ay7n6yz41EqJ-K2mrbKT6AH1nmPWB9rRilkNWXRMYTqTleF-9bO/Queen_Anne's_Lace_Ditsy_Floral_in_Muted_Blue_and_Cream.jpg", alt: "Queen Anne's Lace Ditsy Floral in Muted Blue and Cream" },
  { slug: 'queen-annes-lace-blue', title: "Queen Anne's Lace Ditsy Floral in Muted Blue", src: "https://img.spoonflower.com/c/21460717/p/f/m/zAanx-yzhmQWt1fJZEz7RxTgUkb0Fkwjql36V8WTAFEgJakB2oVk/Queen_Anne's_Lace_Ditsy_Floral_in_Muted_Blue.jpg", alt: "Queen Anne's Lace Ditsy Floral in Muted Blue" },
  { slug: 'queen-annes-lace-blue-white', title: "Queen Anne's Lace Ditsy Floral in Muted Blue and White", src: "https://img.spoonflower.com/c/21459630/p/f/m/f-iu3qVcv7BMiw0MCcit2_tkr1OUW_3siZY8L6GqV0jhZLdY8aI8/Queen_Anne's_Lace_Ditsy_Floral_in_Muted_Blue_and_White.jpg", alt: "Queen Anne's Lace Ditsy Floral in Muted Blue and White" },
  { slug: 'vintage-bee-stripe-mustard-yellow', title: 'Vintage Bee Stripe in Mustard and Warm Yellow', src: 'https://img.spoonflower.com/c/21454939/p/f/m/EI7ZuKB5lD9xsFNvVAU45RVLnz7tNdCP1XabxI3oyGJXfsg9Aj-5/Vintage_Bee_Stripe_in_Mustard_and_Warm_Yellow.jpg', alt: 'Vintage Bee Stripe in Mustard and Warm Yellow' },
  { slug: 'vintage-bee-stripe-warm-yellow', title: 'Vintage Bee Stripe in Warm Yellow', src: 'https://img.spoonflower.com/c/21455004/p/f/m/ogjKvAGU2FRrEeS-sOkyIsNdXjdff8m_aPRDwiFfI_R-kSdnDBfL/Vintage_Bee_Stripe_in_Warm_Yellow.jpg', alt: 'Vintage Bee Stripe in Warm Yellow' },
  { slug: 'country-retro-buttercup-bands-cream', title: 'Country Retro Delicate Buttercup Florals in Soft Striped Bands on Cream', src: 'https://img.spoonflower.com/c/21400607/p/f/m/bD_cqFSXwitxVuBbyzhMejg0a_ASLVQm5JkECsrvT4XtrMk1Qsy7/Country_Retro_Delicate_Buttercup_Florals_in_Soft_Striped_Bands_on_Cream.jpg', alt: 'Country Retro Delicate Buttercup Florals in Soft Striped Bands on Cream' },
  { slug: 'country-retro-buttercup-bands-blue', title: 'Country Retro Buttercup Florals in Soft Striped Bands on Blue', src: 'https://img.spoonflower.com/c/21400529/p/f/m/e7Dn8xhgfBXCm5Iun6XJWrNWh5bUwJx6kpdFb9n3H7A3uVkp9zi6/Country_Retro_Buttercup_Florals_in_Soft_Striped_Bands_on_Blue.jpg', alt: 'Country Retro Buttercup Florals in Soft Striped Bands on Blue' },
  { slug: 'country-retro-gingham-check', title: 'Country Retro Gingham Check in Muted Blue Mustard and Cream', src: 'https://img.spoonflower.com/c/21392860/p/f/m/aMguXPoe8XOM33U_v21fZZ1oa1O45JfybPfN_XMamtBBI7PBPLDj/Country_Retro_Gingham_Check_in_Muted_Blue_Mustard_and_Cream.jpg', alt: 'Country Retro Gingham Check in Muted Blue Mustard and Cream' },
  { slug: 'country-retro-buttercup-vertical-stripes', title: 'Country Retro Buttercup Florals in Vertical Stripes on Muted Blue', src: 'https://img.spoonflower.com/c/21376509/p/f/m/RUxoFNrBuYwqwrsEctNyv1lSGcuQPP3UloSS4UW1HyBeeXvVqoFe/Country_Retro_Buttercup_Florals_in_Vertical_Stripes_on_Muted_Blue.jpg', alt: 'Country Retro Buttercup Florals in Vertical Stripes on Muted Blue' },
  { slug: 'country-retro-buttercup-bands', title: 'Country Retro Buttercup Florals in Soft Striped Bands', src: 'https://img.spoonflower.com/c/21376446/p/f/m/38maE3yeri3W86UyKj1W-eNapheioT5HZKFds9I7BLXOuK5ipSc2/Country_Retro_Buttercup_Florals_in_Soft_Striped_Bands.jpg', alt: 'Country Retro Buttercup Florals in Soft Striped Bands' },
  { slug: 'retro-ditsy-prairie-florals-denim-blue-yellow-large', title: 'Retro Ditsy Prairie Florals in Muted Denim Blue and Soft Yellow (large)', src: 'https://img.spoonflower.com/c/21375269/p/f/m/V_xX5Bl1uevhF8EZ_1bxg45onEr0gKNfq0FJpKy2A6J7vSHS4EyB/(l)_Retro_Ditsy_Prairie_Florals_in_Muted_Denim_Blue_and_Soft_Yellow.jpg', alt: 'Retro Ditsy Prairie Florals in Muted Denim Blue and Soft Yellow large' },
  { slug: 'soft-prairie-garden-warm-natural-beige-large', title: 'Soft Prairie Garden Warm Natural Beige (large)', src: 'https://img.spoonflower.com/c/21340627/p/f/m/DSir95VHw4ZVPEUx8AMxvTO3PF_2-tc1z5LVwn-wqfvUnqb3ber7/(l)_Soft_Prairie_Garden_Warm_Natural_Beige.jpg', alt: 'Soft Prairie Garden Warm Natural Beige large' },
  { slug: 'soft-prairie-garden-denim-blue', title: 'Soft Prairie Garden Muted Denim Blue', src: 'https://img.spoonflower.com/c/21315638/p/f/m/KrIQIDU2CUblL7gRKV5DO4XaKmX1pgefUvFM0EpxrzI9pqr0_x7x/Soft_Prairie_Garden_Muted_Denim_Blue.jpg', alt: 'Soft Prairie Garden Muted Denim Blue' },
  { slug: 'soft-prairie-garden-mustard', title: 'Soft Prairie Garden Mustard', src: 'https://img.spoonflower.com/c/21326141/p/f/m/dbMGVktxaArjm28k6c1tk7Nz8EZhv39YK24kIfOS5TcsCcjTMgun/Soft_Prairie_Garden_Mustard.jpg', alt: 'Soft Prairie Garden Mustard' },
  { slug: 'soft-prairie-garden-warm-natural-beige-small', title: 'Soft Prairie Garden Warm Natural Beige (small)', src: 'https://img.spoonflower.com/c/21340546/p/f/m/EWaTzQQrUY7aMqnq-uTVdMOOMu3pC0iK6_bgNsEqppJL71icWSe9/(s)_Soft_Prairie_Garden_Warm_Natural_Beige.jpg', alt: 'Soft Prairie Garden Warm Natural Beige small' },
]
